spring.application.name=twofactor

server.port=8083

logging.level.org.springframework.security=DEBUG

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html


server.servlet.session.timeout=1800
