spring.application.name=twofactor

server.port=8083

logging.level.org.springframework.security=DEBUG

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html


server.servlet.session.timeout=1800

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chiranjeevigounivalla@gmail.com
spring.mail.password=gmkf bgfdgdfjqr arag zpiv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

